In [ ]:
import pandas as pd

Muestra un DataFrame con los datos de la siguiente tabla:

```
  Mes     Ingresos     Gastos
  Enero   21500        17000
  Febrero 17600        15400
  Marzo   25000        19200
  Abril   34800        22500
```

In [ ]:
datos = {"Mes": ["Enero", "Febrero", "Marzo", "Abril"], "Ingresos":[21500, 17600, 25000, 34800], "Gastos":[17000, 15400, 19200, 22500]}

df = pd.DataFrame(datos)

print(df)

       Mes  Ingresos  Gastos
0    Enero     21500   17000
1  Febrero     17600   15400
2    Marzo     25000   19200
3    Abril     34800   22500

Escribe una funcion que reciba el DataFrame del ejercicio anterior y devuelva el beneficio total de cada mes (Ingresos - Gastos).

In [ ]:

def Utilidad(datos):
  df["Utilidad"] = df["Ingresos"] - df["Gastos"]

  return df

In [ ]:
Utilidad(df)

       Mes  Ingresos  Gastos  Utilidad
0    Enero     21500   17000      4500
1  Febrero     17600   15400      2200
2    Marzo     25000   19200      5800
3    Abril     34800   22500     12300

En github he subido el fichero titanic.csv (obtenido de kaggle.com) y realizar las siguientes operaciones.


1.   Generar un DataFrame con los datos del fichero indicado.
2.   Mostrar sus dimensiones, el numero de datos que contiene, nombres de las columnas y filas, tipos de datos de las columnas y mostrar las 5 primeras filas y las 5 ultimas.
3.   Mostrar los datos del pasajero con identificador 121.
4.   Mostrar las filas impares del DataFrame.
5.   Cuantas personas sobrevivieron y murieron, indicar porcentaje.
6.   Personas que estaban en segunda clase por orden alfabetico.
7.   Eliminar los pasajeros que no tengan registrada su edad o sea nula.
8.   Porcentaje de personas que murieron por cada clase.
9.   Edad media de hombres y mujeres que viajaban en cada clase.
10.  Añadir nueva columna que indique si el pasajero era menor de edad o no.
11.  Mostrar el porcentaje de menores y mayores de edad que sobrevivieron.

In [ ]:
from os import read
df_titanic = pd.read_csv("/content/sample_data/titanic.csv")

In [ ]:
print(df_titanic)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [ ]:
dimensiones = df_titanic.shape
tamaño = df_titanic.size
print(f"Filas: {dimensiones[0]}, Columnas: {dimensiones[1]}, Tamaño: {tamaño}")

Filas: 891, Columnas: 12, Tamaño: 10692

In [ ]:
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
print("Primeras 5 filas del df\n")
df_titanic.head()

Primeras 5 filas del df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
print("\nUltimas 5 filas del df")
df_titanic.tail()

Ultimas 5 filas del df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
pasajero_121 = df_titanic[df_titanic["PassengerId"] == 121]

print(pasajero_121)

     PassengerId  Survived  Pclass                         Name   Sex   Age  \
120          121         0       2  Hickman, Mr. Stanley George  male  21.0

     SibSp  Parch        Ticket  Fare Cabin Embarked
120      2      0  S.O.C. 14879  73.5   NaN        S

In [ ]:
df_titanic.loc[121]

PassengerId                           122
Survived                                0
Pclass                                  3
Name           Moore, Mr. Leonard Charles
Sex                                  male
Age                                   NaN
SibSp                                   0
Parch                                   0
Ticket                          A4. 54510
Fare                                 8.05
Cabin                                 NaN
Embarked                                S
Name: 121, dtype: object

In [ ]:
df_impar = df_titanic[df_titanic["PassengerId"] % 2 != 0]

print(df_impar)

     PassengerId  Survived  Pclass  \
0              1         0       3
2              3         1       3
4              5         0       3
6              7         0       1
8              9         1       3
..           ...       ...     ...
882          883         0       3
884          885         0       3
886          887         0       2
888          889         0       3
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
4                             Allen, Mr. William Henry    male  35.0      0
6                              McCarthy, Mr. Timothy J    male  54.0      0
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
..                                                 ...     ...   ...    ...
882                       Dahlberg, Miss. Gerda Ulrika  female  22.0      0
884                             Sutehall, Mr. Henry Jr    male  25.0      0
886                              Montvila, Rev. Juozas    male  27.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
2        0  STON/O2. 3101282   7.9250   NaN        S
4        0            373450   8.0500   NaN        S
6        0             17463  51.8625   E46        S
8        2            347742  11.1333   NaN        S
..     ...               ...      ...   ...      ...
882      0              7552  10.5167   NaN        S
884      0   SOTON/OQ 392076   7.0500   NaN        S
886      0            211536  13.0000   NaN        S
888      2        W./C. 6607  23.4500   NaN        S
890      0            370376   7.7500   NaN        Q

[446 rows x 12 columns]

In [ ]:
df_sobrevivientes = df_titanic[df_titanic["Survived"] == 1]

print(df_sobrevivientes)

dimensiones_sobrevientes = df_sobrevivientes.shape

porcentaje_sobrevivientes = (dimensiones_sobrevientes[0] * 100) / dimensiones[0]

print(f"\nPorcentaje de sobrevientes: {porcentaje_sobrevivientes} %")

     PassengerId  Survived  Pclass  \
1              2         1       1
2              3         1       3
3              4         1       1
8              9         1       3
9             10         1       2
..           ...       ...     ...
875          876         1       3
879          880         1       1
880          881         1       2
887          888         1       1
889          890         1       1

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
..                                                 ...     ...   ...    ...
875                   Najib, Miss. Adele Kiamie "Jane"  female  15.0      0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
889                              Behr, Mr. Karl Howell    male  26.0      0

     Parch            Ticket     Fare Cabin Embarked
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
8        2            347742  11.1333   NaN        S
9        0            237736  30.0708   NaN        C
..     ...               ...      ...   ...      ...
875      0              2667   7.2250   NaN        C
879      1             11767  83.1583   C50        C
880      1            230433  26.0000   NaN        S
887      0            112053  30.0000   B42        S
889      0            111369  30.0000  C148        C

[342 rows x 12 columns]

Porcentaje de sobrevientes: 38.38383838383838 %

In [ ]:
df_bajas = df_titanic[df_titanic["Survived"] == 0]

print(df_bajas)

dimensiones_bajas = df_bajas.shape

porcentaje_bajas = (dimensiones_bajas[0] * 100) / dimensiones[0]

print(f"\nPorcentaje de bajas: {porcentaje_bajas} %")

     PassengerId  Survived  Pclass                                      Name  \
0              1         0       3                   Braund, Mr. Owen Harris
4              5         0       3                  Allen, Mr. William Henry
5              6         0       3                          Moran, Mr. James
6              7         0       1                   McCarthy, Mr. Timothy J
7              8         0       3            Palsson, Master. Gosta Leonard
..           ...       ...     ...                                       ...
884          885         0       3                    Sutehall, Mr. Henry Jr
885          886         0       3      Rice, Mrs. William (Margaret Norton)
886          887         0       2                     Montvila, Rev. Juozas
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
890          891         0       3                       Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch           Ticket     Fare Cabin Embarked
0      male  22.0      1      0        A/5 21171   7.2500   NaN        S
4      male  35.0      0      0           373450   8.0500   NaN        S
5      male   NaN      0      0           330877   8.4583   NaN        Q
6      male  54.0      0      0            17463  51.8625   E46        S
7      male   2.0      3      1           349909  21.0750   NaN        S
..      ...   ...    ...    ...              ...      ...   ...      ...
884    male  25.0      0      0  SOTON/OQ 392076   7.0500   NaN        S
885  female  39.0      0      5           382652  29.1250   NaN        Q
886    male  27.0      0      0           211536  13.0000   NaN        S
888  female   NaN      1      2       W./C. 6607  23.4500   NaN        S
890    male  32.0      0      0           370376   7.7500   NaN        Q

[549 rows x 12 columns]

Porcentaje de bajas: 61.61616161616162 %

In [ ]:
segunda_clase = df_sobrevivientes[df_sobrevivientes["Pclass"] == 2]

segunda_clase = segunda_clase.sort_values(by="Name")

print(segunda_clase)

     PassengerId  Survived  Pclass  \
874          875         1       2
518          519         1       2
327          328         1       2
543          544         1       2
546          547         1       2
..           ...       ...     ...
750          751         1       2
58            59         1       2
472          473         1       2
673          674         1       2
17            18         1       2

                                                  Name     Sex   Age  SibSp  \
874              Abelson, Mrs. Samuel (Hannah Wizosky)  female  28.0      1
518  Angle, Mrs. William A (Florence "Mary" Agnes H...  female  36.0      1
327                            Ball, Mrs. (Ada E Hall)  female  36.0      0
543                                  Beane, Mr. Edward    male  32.0      1
546                  Beane, Mrs. Edward (Ethel Clarke)  female  19.0      1
..                                                 ...     ...   ...    ...
750                                  Wells, Miss. Joan  female   4.0      1
58                        West, Miss. Constance Mirium  female   5.0      1
472            West, Mrs. Edwy Arthur (Ada Mary Worth)  female  33.0      1
673                              Wilhelms, Mr. Charles    male  31.0      0
17                        Williams, Mr. Charles Eugene    male   NaN      0

     Parch      Ticket   Fare Cabin Embarked
874      0   P/PP 3381  24.00   NaN        C
518      0      226875  26.00   NaN        S
327      0       28551  13.00     D        S
543      0        2908  26.00   NaN        S
546      0        2908  26.00   NaN        S
..     ...         ...    ...   ...      ...
750      1       29103  23.00   NaN        S
58       2  C.A. 34651  27.75   NaN        S
472      2  C.A. 34651  27.75   NaN        S
673      0      244270  13.00   NaN        S
17       0      244373  13.00   NaN        S

[87 rows x 12 columns]

In [ ]:
df_titanic_filtrado = df_titanic.dropna(subset="Age")

print(df_titanic_filtrado)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
885          886         0       3
886          887         0       2
887          888         1       1
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
885      5            382652  29.1250   NaN        Q
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[714 rows x 12 columns]

In [ ]:
primera_clase = df_sobrevivientes[df_sobrevivientes["Pclass"] == 1]

sobrevivientes_1ra_clase = primera_clase[primera_clase["Survived"] == 1]

dimensiones_1ra_clase_survived = sobrevivientes_1ra_clase.shape

porcentaje_1ra_clase = (dimensiones_1ra_clase_survived[0] * 100) / dimensiones[0]


segunda_clase = df_sobrevivientes[df_sobrevivientes["Pclass"] == 2]

sobrevivientes_2da_clase = segunda_clase[segunda_clase["Survived"] == 1]

dimensiones_2da_clase_survived = sobrevivientes_2da_clase.shape

porcentaje_2da_clase = (dimensiones_2da_clase_survived[0] * 100) / dimensiones[0]



tercera_clase = df_sobrevivientes[df_sobrevivientes["Pclass"] == 3]

sobrevivientes_3ra_clase = tercera_clase[tercera_clase["Survived"] == 1]

dimensiones_3ra_clase_survived = sobrevivientes_3ra_clase.shape

porcentaje_3ra_clase = (dimensiones_3ra_clase_survived[0] * 100) / dimensiones[0]


print(f"Porcentajes\n1ra Clase:   {porcentaje_1ra_clase} %\n2da Clase:  {porcentaje_2da_clase} %\n3ra Clase:  {porcentaje_3ra_clase} %")

Porcentajes
1ra Clase:   15.26374859708193 %
2da Clase:  9.764309764309765 %
3ra Clase:  13.35578002244669 %

In [ ]:
primera_clase_filtrado = df_titanic_filtrado[df_titanic_filtrado["Pclass"]== 1]
#Hombres 1ra clase
hombres_1ra_clase = primera_clase_filtrado[primera_clase_filtrado["Sex"]== "male"]

dimensiones_hombres_1ra_clase = hombres_1ra_clase.shape

suma_edades_hombres_1ra_clase = hombres_1ra_clase["Age"].sum()

promedio_edades_1ra_clase_hombres = suma_edades_hombres_1ra_clase / dimensiones_hombres_1ra_clase[0]
#Mujeres 1ra clase
mujeres_1ra_clase = primera_clase_filtrado[primera_clase_filtrado["Sex"]== "female"]

dimensiones_mujeres_1ra_clase = mujeres_1ra_clase.shape

suma_edades_mujeres_1ra_clase = mujeres_1ra_clase["Age"].sum()

promedio_edades_1ra_clase_mujeres = suma_edades_mujeres_1ra_clase / dimensiones_mujeres_1ra_clase[0]



segunda_clase_filtrado = df_titanic_filtrado[df_titanic_filtrado["Pclass"]== 2]
#Hombres 2da clase
hombres_2da_clase = segunda_clase_filtrado[segunda_clase_filtrado["Sex"]== "male"]

dimensiones_hombres_2da_clase = hombres_2da_clase.shape

suma_edades_hombres_2da_clase = hombres_2da_clase["Age"].sum()

promedio_edades_2da_clase_hombres = suma_edades_hombres_2da_clase / dimensiones_hombres_2da_clase[0]
#Mujeres 2da clase
mujeres_2da_clase = segunda_clase_filtrado[segunda_clase_filtrado["Sex"]== "female"]

dimensiones_mujeres_2da_clase = mujeres_2da_clase.shape

suma_edades_mujeres_2da_clase = mujeres_2da_clase["Age"].sum()

promedio_edades_2da_clase_mujeres = suma_edades_mujeres_2da_clase / dimensiones_mujeres_2da_clase[0]





tercera_clase_filtrado = df_titanic_filtrado[df_titanic_filtrado["Pclass"]== 3]
#Hombres 3ra clase
hombres_3ra_clase = tercera_clase_filtrado[tercera_clase_filtrado["Sex"]== "male"]

dimensiones_hombres_3ra_clase = hombres_3ra_clase.shape

suma_edades_hombres_3ra_clase = hombres_3ra_clase["Age"].sum()

promedio_edades_3ra_clase_hombres = suma_edades_hombres_3ra_clase / dimensiones_hombres_3ra_clase[0]
#Mujeres 3ra clase
mujeres_3ra_clase = tercera_clase_filtrado[tercera_clase_filtrado["Sex"]== "female"]

dimensiones_mujeres_3ra_clase = mujeres_3ra_clase.shape

suma_edades_mujeres_3ra_clase = mujeres_3ra_clase["Age"].sum()

promedio_edades_3ra_clase_mujeres = suma_edades_mujeres_3ra_clase / dimensiones_mujeres_3ra_clase[0]




print(f"Edad promedio hombres 1ra clase: {round(promedio_edades_1ra_clase_hombres,0)}\nEdad promedio mujeres 1ra clase: {round(promedio_edades_1ra_clase_mujeres,0)}\nEdad promedio hombres 2da clase: {round(promedio_edades_2da_clase_hombres,0)}\nEdad promedio mujeres 2da clase: {round(promedio_edades_2da_clase_mujeres,0)}\nEdad promedio hombres 3ra clase: {round(promedio_edades_3ra_clase_hombres,0)}\nEdad promedio mujeres 3ra clase: {round(promedio_edades_3ra_clase_mujeres,0)}")

Edad promedio hombres 1ra clase: 41.0
Edad promedio mujeres 1ra clase: 35.0
Edad promedio hombres 2da clase: 31.0
Edad promedio mujeres 2da clase: 29.0
Edad promedio hombres 3ra clase: 27.0
Edad promedio mujeres 3ra clase: 22.0

In [ ]:
df_titanic_filtrado["MayorEdad"] = df_titanic_filtrado['Age'].apply(lambda x: 1 if x > 21 else 0)

print(df_titanic_filtrado)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
885          886         0       3
886          887         0       2
887          888         1       1
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked  MayorEdad
0        0         A/5 21171   7.2500   NaN        S          1
1        0          PC 17599  71.2833   C85        C          1
2        0  STON/O2. 3101282   7.9250   NaN        S          1
3        0            113803  53.1000  C123        S          1
4        0            373450   8.0500   NaN        S          1
..     ...               ...      ...   ...      ...        ...
885      5            382652  29.1250   NaN        Q          1
886      0            211536  13.0000   NaN        S          1
887      0            112053  30.0000   B42        S          0
889      0            111369  30.0000  C148        C          1
890      0            370376   7.7500   NaN        Q          1

[714 rows x 13 columns]

/tmp/ipykernel_1255/2082067564.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_titanic_filtrado["MayorEdad"] = df_titanic_filtrado['Age'].apply(lambda x: 1 if x > 21 else 0)

In [ ]:
dimensiones_titanic_filtrado = df_titanic_filtrado.shape

df_sobrevivientes = df_titanic_filtrado[df_titanic_filtrado["Survived"] == 1]

df_sobrevivientes_menores = df_sobrevivientes[df_sobrevivientes["MayorEdad"] == 0]

dimensiones_sobrevientes_menores = df_sobrevivientes_menores.shape

porcentaje_sobrevivientes_menores = (dimensiones_sobrevientes_menores[0] * 100) / dimensiones_titanic_filtrado[0]

df_sobrevivientes_mayores = df_sobrevivientes[df_sobrevivientes["MayorEdad"] == 1]

dimensiones_sobrevientes_mayores = df_sobrevivientes_mayores.shape

porcentaje_sobrevivientes_mayores = (dimensiones_sobrevientes_mayores[0] * 100) / dimensiones_titanic_filtrado[0]


print(f"\nPorcentaje de sobrevientes menores de edad: {round(porcentaje_sobrevivientes_menores,0)} %\nPorcentaje de sobrevientes mayores de edad: {round(porcentaje_sobrevivientes_mayores,0)} %\n")

Porcentaje de sobrevientes menores de edad: 12.0 %
Porcentaje de sobrevientes mayores de edad: 28.0 %